name: Release Workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      INTEGRATION: authenticated
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get release version
        id: version
        shell: bash
        run: |
          version="${GITHUB_REF_NAME#v}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Set version number
        shell: bash
        run: |
          sed -i '/INTEGRATION_VERSION = /c\INTEGRATION_VERSION = "${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/${INTEGRATION}/const.py"
          jq '.version = "${{ steps.version.outputs.version }}"' \
            "${{ github.workspace }}/custom_components/${INTEGRATION}/manifest.json" > tmp \
            && mv -f tmp "${{ github.workspace }}/custom_components/${INTEGRATION}/manifest.json"

      - name: Validate release data
        shell: bash
        run: |
          if ! grep -q 'INTEGRATION_VERSION = "${{ steps.version.outputs.version }}"' "${{ github.workspace }}/custom_components/${INTEGRATION}/const.py"; then
            echo "The version in custom_components/${INTEGRATION}/const.py was not correct"
            grep INTEGRATION_VERSION "${{ github.workspace }}/custom_components/${INTEGRATION}/const.py"
            exit 1
          fi
          manifestversion=$(jq -r '.version' "${{ github.workspace }}/custom_components/${INTEGRATION}/manifest.json")
          if [ "$manifestversion" != "${{ steps.version.outputs.version }}" ]; then
            echo "The version in custom_components/${INTEGRATION}/manifest.json was not correct"
            echo "$manifestversion"
            exit 1
          fi

      - name: Create zip file for the integration
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/${INTEGRATION}"
          zip "${{ github.workspace }}/${INTEGRATION}.zip" -r ./ -x "*/__pycache__/*" "*.pyc"

      - name: Upload the zip file as a release asset
        uses: softprops/action-gh-release@v2
        with:
          files: authenticated.zip
